-- Shares table
-- Tracks every share event generated by a user for a podcast or episode.
-- share_token is the unique opaque token included in the shareable URL.
-- platform records where the link was shared (optional analytics dimension).

CREATE TABLE IF NOT EXISTS public.shares (
    id          UUID        NOT NULL DEFAULT gen_random_uuid(),
    user_id     UUID,
    target_type TEXT        NOT NULL CHECK (target_type IN ('podcast', 'episode')),
    target_id   UUID        NOT NULL,
    share_token TEXT        NOT NULL DEFAULT gen_random_uuid()::TEXT,
    platform    TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_shares       PRIMARY KEY (id),
    CONSTRAINT uq_shares_token UNIQUE (share_token),
    CONSTRAINT fk_shares_users FOREIGN KEY (user_id)
        REFERENCES public.users (id)
        ON UPDATE NO ACTION
        ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_shares_user_id    ON public.shares (user_id);
CREATE INDEX IF NOT EXISTS idx_shares_target     ON public.shares (target_type, target_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_shares_token ON public.shares (share_token);
